version: '3'
services:
  chat:
    build: .
    container_name: chat
    command: bundle exec guard --no-bundler-warning --no-interactions
    tty: true
    stdin_open: true
    user: app
    # user: root
    volumes:
      - ~/.ssh:/home/app/.ssh
      - .:/usr/src/app
      - chatbundle:/bundle
    tmpfs:
      - /usr/src/app/tmp/pids:mode=777,size=4m,uid=1000,gid=1000
    ports:
      - "3000:3000"
      - "3035:3035"
      - "35729:35729"
      - "1234:1234"
      - "26162:26162"
    depends_on:
      - chatdb
    environment: 
      TZ: America/New_York
      PGHOST: chatdb
      PGUSER: postgres
      PGPASSWORD: postgres
  chatdb:
    image: postgres
    container_name: chatdb
    volumes:
      - chatdata:/var/lib/postgresql/data
    environment:
      TZ: America/New_York
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  chatbundle:
    external: true
  chatdata:
    external: true